// project-manager-vue/src/components/form/RegisterForm.vue
<template>
  <a-form
    layout="horizontal"
    :model="formState"
    @finish="handleFinish"
    @finishFailed="handleFinishFailed"
  >
    <a-form-item>
      <a-input v-model:value="formState.user" placeholder="Username">
        <template #prefix>
          <UserOutlined style="color: rgba(0, 0, 0, 0.25)" />
        </template>
      </a-input>
    </a-form-item>
    <a-form-item>
      <a-input
        v-model:value="formState.password"
        type="password"
        placeholder="Password"
      >
        <template #prefix>
          <LockOutlined style="color: rgba(0, 0, 0, 0.25)" />
        </template>
      </a-input>
    </a-form-item>
    <a-form-item>
      <a-button
        type="primary"
        class="w-full"
        html-type="submit"
        :disabled="formState.user === '' || formState.password === ''"
      >
        Registrovat se
      </a-button>
    </a-form-item>
  </a-form>
</template>
<script lang="ts">
import { UserOutlined, LockOutlined } from "@ant-design/icons-vue";
import { defineComponent, reactive } from "vue";
import type { UnwrapRef } from "vue";
import { notification, type FormProps } from "ant-design-vue";
import router from "@/router";

interface FormState {
  user: string;
  password: string;
}
export default defineComponent({
  components: {
    UserOutlined,
    LockOutlined,
  },
  setup() {
    const formState: UnwrapRef<FormState> = reactive({
      user: "",
      password: "",
    });
    const handleFinish: FormProps["onFinish"] = (values) => {
       const requestOptions = {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formState),
      };
       fetch("/api/User/Register", requestOptions)
        .then((response) => {
          notification["success"]({
            message: "Registrace proběhla úspěšně!",
            description: "Vaše registrace proběhla v pořádku, nyní budete přesměrování na hlavní stránku.",
          });
          router.push({ path: "/auth/login" });
        })
        .catch((err) => {
          notification["error"]({
            message: "Registrace se nepovedla!",
            description:
              "Zkuste zadat údaje správně",
          });
        });
    };
    const handleFinishFailed: FormProps["onFinishFailed"] = (errors) => {
      console.log(errors);
    };
    return {
      formState,
      handleFinish,
      handleFinishFailed,
    };
  },
});
</script>

// project-manager-react/src/components/Register-form.js
import { Button, Form, Input, notification } from "antd";
import { UserOutlined } from "@ant-design/icons";
import { LockOutlined } from "@ant-design/icons";
import { useNavigate } from "react-router-dom";

export const RegisterForm = () => {
  const navigate = useNavigate();
  const onFinish = async (values) => {
    const requestOptions = {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    };
    await fetch("/api/User/Register", requestOptions)
      .then((response) => {
        if(response.ok){
            notification["success"]({
                message: "Registrace proběhla úspěšně!",
                description: "Vaše registrace proběhla v pořádku, nyní budete přesměrování na hlavní stránku.",
              });
              navigate("/auth/login");
        } else {
            notification["error"]({
                message: "Registrace se nepovedla!",
                description:
                  "Zkuste zadat údaje správně",
              });
        }
      })
  };

  return (
    <Form
      name="basic"
      wrapperCol={{ span: 24 }}
      initialValues={null}
      onFinish={onFinish}
      autoComplete="true"
    >
      <Form.Item
        name="Email"
        rules={[{ required: true, message: "Please input your username!" }]}
      >
        <Input size="large" placeholder="Uživatelské jméno" />
      </Form.Item>

      <Form.Item
        name="Password"
        rules={[{ required: true, message: "Please input your password!" }]}
      >
        <Input.Password size="large" placeholder="Heslo"/>
      </Form.Item>

      <Form.Item wrapperCol={{ span: 24 }}>
        <Button
          type="primary"
          htmlType="submit"
          className="uppercase font-semibold py-3 h-auto rounded-md w-full"
        >
       Registrovat se
        </Button>
      </Form.Item>
    </Form>
  );
};
