// project-manager-angular/src/app/layouts/admin-layout/admin-layout.component.ts
import { DatePipe } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AccountService } from 'src/app/services/account.service';

@Component({
  selector: 'app-admin-layout',
  templateUrl: './admin-layout.component.html',
  styleUrls: ['./admin-layout.component.scss']
})
export class AdminLayoutComponent implements OnInit {

  public isUserLoggedIn = false;

  public user$ = this.accountService.getLoggedUser$;

  mobileMenu = false;

  footerDate = new Date();

  currentVersion: any;

  constructor(private accountService: AccountService, private router: Router,
    public datepipe: DatePipe) {
  }

  ngOnInit(): void {
  }

  logout(): void {
    this.accountService.logout().subscribe(() => {
      this.router.navigate(['/auth/login']);
    });
  }

  textForAvatar(name: string) {
    if (name) {
      if (name.length > 1) {
        return name.substring(0, 2).toUpperCase();
      }
    }
    return 'U';
  }

  showMobile(){
    this.mobileMenu = true;
  }

  close(){
    this.mobileMenu = false;
  }

}

<nz-layout class="main-layout">
  <nz-header class="px-3 bg-primary-900">
    <div class="logo">
      <h1 class="inline-block float-left py-4 text-white text-3xl">Project Manager</h1>

      </div>
    <ul nz-menu nzTheme="dark" nzMode="horizontal" class="header-menu float-right ">
      <li nz-menu-item *ngIf="(user$ | async)" class="user-section" [nzSelected]="false">
        <nz-avatar nzSize="large" nzIcon="user" class="float-left inline-block mt-4 mr-5"></nz-avatar>
        <section class="float-left flex py-2 flex-col justify-evenly h-full text-white text user-info"><span
            class="text-lg">{{(user$ | async)!.userName}}</span> <span class="text-slate-400">{{(user$ | async)!.userName}}</span></section>
      </li>
      <li nz-menu-item (click)="logout()"><i nz-icon nzType="logout" nzTheme="outline" class="mr-2"></i> Odhlásit se
      </li>
    </ul>
  </nz-header>
  <nz-layout>
    <nz-sider nzWidth="250px" nzTheme="light">
      <ul nz-menu nzMode="inline" class="sider-menu">
        <li nz-menu-item nzMatchRouter><a routerLink="/projects"><i nz-icon nzType="dashboard"></i> <span>Projekty</span></a></li>
        <li nz-menu-item nzMatchRouter><a routerLink="/tasks"><i nz-icon nzType="bars"></i> <span>Úkoly</span></a></li>
        <li nz-menu-item nzMatchRouter><a routerLink="/users"><i nz-icon nzType="team"></i> <span>Uživatelé</span></a></li>
      </ul>
    </nz-sider>
    <nz-layout class="inner-layout">

      <nz-content>
        <router-outlet></router-outlet>
      </nz-content>
    </nz-layout>
  </nz-layout>
</nz-layout>

// project-manager-vue/src/views/AdminLayout.vue
<script lang="ts">
import { RouterView, RouterLink } from "vue-router";
import router from "@/router";
import { notification } from "ant-design-vue";
import {
  DashboardOutlined,
  LogoutOutlined,
  TeamOutlined,
  UserOutlined,
} from '@ant-design/icons-vue';
import { defineComponent, ref } from 'vue';
import { UserDTO } from "@/models/user.dto";
export default defineComponent({
  components: {
    DashboardOutlined,
    TeamOutlined,
    UserOutlined,
    LogoutOutlined
  },
  methods: {
    async logout() {
      try {
        await fetch('/api/User/Logout', { method: 'POST' });
        notification["success"]({
          message: "Odhlášení proběhlo úspěšně!",
          description: "Přesměrovávám na login.",
        });
      } catch (err) {
        console.log(err);
      }
      router.push({ path: "/auth/login" });
    }
  },
  data() {
    return {
      user: new UserDTO(),
      // eslint-disable-next-line vue/no-dupe-keys
      footer: new Date().getFullYear(),
      collapsed: ref<boolean>(false),
      selectedKeys: ref<string[]>(['1']),
    };
  },
  async created() {
    const data = await (await fetch('/api/User/UserInfo')).json();
    this.user = data;
  }
});
</script>

<template>
  <a-layout style="min-height: 100vh">
    <a-layout-header class="header px-3 bg-primary-900">
      <div class="logo">
        <h1 class="inline-block float-left pt-3 text-white text-3xl" style="margin-right: calc(75vw - 248px);">Project
          Manager</h1>
      </div>
      <a-menu v-model:selectedKeys="selectedKeys" theme="dark" mode="horizontal" class="bg-primary-900 header-menu"
        :style="{ lineHeight: '64px' }">
        <a-menu-item key="user" class="user-section">
          <a-avatar size="large" class="float-left inline-block mt-4 mr-5">
            <template #icon>
              <UserOutlined />
            </template>
          </a-avatar>
          <section v-if="user" class="float-left flex py-2 flex-col justify-evenly h-full text-white text user-info">
            <span class="text-lg">{{ user.userName }}</span>
            <span class="text-slate-400">{{ user.userName }}</span>
          </section>
        </a-menu-item>
        <a-menu-item key="logout" v-on:click="logout()">
          <logout-outlined class="mr-2" /> Odhlásit se
        </a-menu-item>
      </a-menu>
    </a-layout-header>
    <a-layout>
      <a-layout-sider width="250" style="background: #fff">
        <a-menu v-model:selectedKeys="selectedKeys" theme="light" mode="inline">
          <a-menu-item key="1">
            <RouterLink to="/admin/projects">
              <dashboard-outlined />
              <span>Projekty</span>
            </RouterLink>
          </a-menu-item>
          <a-menu-item key="2">
            <RouterLink to="/admin/users">
              <team-outlined />
              <span>Uživatelé</span>
            </RouterLink>
          </a-menu-item>
        </a-menu>
      </a-layout-sider>
      <a-layout>
        <RouterView />
      </a-layout>
    </a-layout>
  </a-layout>
</template>

<style>
.anticon {
  vertical-align: 2px;
}

.header-menu {
  background: rgb(11 49 102 / var(--tw-bg-opacity)) !important;
}

.user-info {
  line-height: 64px;
}

.user-info span {
  line-height: initial;
}
</style>
